In [1]:
import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split

# Thai dataset

In [152]:
df = pd.read_csv('original_data/Original_Dataset.csv')
df.head(10)

   Id                                               Text               Type
0   1  [Call](สวัสดีค่ะ เนื่องจากคุณเป็นผู้โชคดีได้รั...               Scam
1   2  [Call](มึงว่างป่ะ ไปกินชาบูกัน) [User](ได้ๆ กี...            General
2   3  [Call](Your Verification key is 123456. Please...  Verification-call
3   4  [Call](เรียนคุณสมชาย ธนาคารกรุงเทพขอแจ้งว่าบัญ...               Scam
4   5  [Call](สวัสดีค่ะ คุณสมหมาย สำนักงานประกันสังคม...           Official
5   6  [Call](เฮ้ เราอยู่แถวเซ็นทรัล อยากเจอป่ะ) [Use...            General
6   7  [Call](รหัส OTP ของคุณคือ 789012 กรุณาอย่าเผยแ...  Verification-call
7   8  [Call](ขอเรียนนายกสรรเพชร กระทรวงสาธารณสุข แจ้...           Official
8   9  [Call](สวัสดีค่ะ พนักงานไปรษณีย์ โทรมาแจ้งว่าพ...               Scam
9  10  [Call](หวัดดี เราคิดถึงแก) [User](คิดถึงเหมือน...            General

In [153]:
# edit columns
df_new = df.drop('Id', axis=1)
df_new = df_new.rename(columns={'Text': 'text', 'Type': 'label'})
df_new.head(10)

                                                text              label
0  [Call](สวัสดีค่ะ เนื่องจากคุณเป็นผู้โชคดีได้รั...               Scam
1  [Call](มึงว่างป่ะ ไปกินชาบูกัน) [User](ได้ๆ กี...            General
2  [Call](Your Verification key is 123456. Please...  Verification-call
3  [Call](เรียนคุณสมชาย ธนาคารกรุงเทพขอแจ้งว่าบัญ...               Scam
4  [Call](สวัสดีค่ะ คุณสมหมาย สำนักงานประกันสังคม...           Official
5  [Call](เฮ้ เราอยู่แถวเซ็นทรัล อยากเจอป่ะ) [Use...            General
6  [Call](รหัส OTP ของคุณคือ 789012 กรุณาอย่าเผยแ...  Verification-call
7  [Call](ขอเรียนนายกสรรเพชร กระทรวงสาธารณสุข แจ้...           Official
8  [Call](สวัสดีค่ะ พนักงานไปรษณีย์ โทรมาแจ้งว่าพ...               Scam
9  [Call](หวัดดี เราคิดถึงแก) [User](คิดถึงเหมือน...            General

In [154]:
# make label to be either 1 (Scam) or 0 (Other)
df_new['label'] = np.where(df_new['label'] == 'Scam', 1, 0)
df_new.head(10)

                                                text  label
0  [Call](สวัสดีค่ะ เนื่องจากคุณเป็นผู้โชคดีได้รั...      1
1  [Call](มึงว่างป่ะ ไปกินชาบูกัน) [User](ได้ๆ กี...      0
2  [Call](Your Verification key is 123456. Please...      0
3  [Call](เรียนคุณสมชาย ธนาคารกรุงเทพขอแจ้งว่าบัญ...      1
4  [Call](สวัสดีค่ะ คุณสมหมาย สำนักงานประกันสังคม...      0
5  [Call](เฮ้ เราอยู่แถวเซ็นทรัล อยากเจอป่ะ) [Use...      0
6  [Call](รหัส OTP ของคุณคือ 789012 กรุณาอย่าเผยแ...      0
7  [Call](ขอเรียนนายกสรรเพชร กระทรวงสาธารณสุข แจ้...      0
8  [Call](สวัสดีค่ะ พนักงานไปรษณีย์ โทรมาแจ้งว่าพ...      1
9  [Call](หวัดดี เราคิดถึงแก) [User](คิดถึงเหมือน...      0

In [155]:
# save the formatted only version to csv

df_new.to_csv('processed_data/formatted_only.csv', index=False)

## Text/Data Processing

In [156]:
# Removing duplicates conversation

print(len(df_new))
df_new.drop_duplicates(subset=['text'], inplace=True)
print(len(df_new))

198
179

### assuming audio is from both side of the conversation

In [157]:
df_both = df_new.copy()
df_both['text'] = df_both['text'].str.strip()
df_both['text'] = df_both['text'].str.replace("[Call]", "")
df_both['text'] = df_both['text'].str.replace("[User]", "")
df_both['text'] = df_both['text'].str.replace("(", "")
df_both['text'] = df_both['text'].str.replace(")", "")
df_both['text'].head(20)

0     สวัสดีค่ะ เนื่องจากคุณเป็นผู้โชคดีได้รับโทรศัพ...
1     มึงว่างป่ะ ไปกินชาบูกัน ได้ๆ กี่โมงล่ะ วันนี้ส...
2     Your Verification key is 123456. Please do not...
3     เรียนคุณสมชาย ธนาคารกรุงเทพขอแจ้งว่าบัญชีของท่...
4     สวัสดีค่ะ คุณสมหมาย สำนักงานประกันสังคม โทรมาแ...
5     เฮ้ เราอยู่แถวเซ็นทรัล อยากเจอป่ะ ไปคาเฟ่ดีไหม...
6     รหัส OTP ของคุณคือ 789012 กรุณาอย่าเผยแพร่หมาย...
7     ขอเรียนนายกสรรเพชร กระทรวงสาธารณสุข แจ้งเตือนส...
8     สวัสดีค่ะ พนักงานไปรษณีย์ โทรมาแจ้งว่าพัสดุของ...
9     หวัดดี เราคิดถึงแก คิดถึงเหมือนกัน ไปเจอกันวัน...
10    รหัสยืนยันสำหรับการรีเซ็ตรหัสผ่านของคุณคือ ABC...
11    สวัสดีค่ะ เรียนเชิญเข้าร่วมสอบสัมภาษณ์งานที่บร...
12                                                  ...
13    ขอข้อมูลเพิ่มเติมเกี่ยวกับสวัสดิการที่ได้รับ ส...
14    สวัสดีค่ะ โรงเรียนอนุบาลรุ่งเรื่อง โทรมาสอบถาม...
15    สวัสดีครับ พนักงาน AIS โทรมาสอบถามว่าคุณต้องกา...
16    เรียนคุณณัฐพล กระทรวงสาธารณสุขโทรมาแจ้งนัดฉีดว...
17    สวัสดีค่ะ ฝ่ายลูกค้าสัมพันธ์ธนาคารกรุงเทพค่ะ แ...
18                   Your OTP for transaction is 736482
19    คุณได้รับเงินคืนจากกรมสรรพากร 1,200 บาท กรุณาก...
Name: text, dtype: object

In [158]:
df_both.to_csv('processed_data/both.csv', index=False)

### assuming audio is only from the other side of the conversation

In [159]:
df_caller = df_new.copy()

pattern = r"\[Call\]\s*\((.*?)\)"
df_caller['text'] = df_caller['text'].str.findall(pattern) #.str.join('')

df_caller_exploded = df_caller.explode('text')

df_caller_joined = df_caller.copy()
df_caller_joined['text'] = df_caller['text'].str.join(' ')

df_caller_exploded.to_csv('processed_data/caller_exploded.csv', index=False)
df_caller_joined.to_csv('processed_data/caller_joined.csv', index=False)

print(df_caller_exploded.head(5))
print()
print(df_caller_joined.head(5))

                                                text  label
0  สวัสดีค่ะ เนื่องจากคุณเป็นผู้โชคดีได้รับโทรศัพ...      1
0  จริงค่ะ หากคุณต้องการรับโทรศัพท์นี้ โปรดติดต่อ...      1
1                            มึงว่างป่ะ ไปกินชาบูกัน      0
1                                วันนี้สัก 6 โมงเย็น      0
2  Your Verification key is 123456. Please do not...      0

                                                text  label
0  สวัสดีค่ะ เนื่องจากคุณเป็นผู้โชคดีได้รับโทรศัพ...      1
1        มึงว่างป่ะ ไปกินชาบูกัน วันนี้สัก 6 โมงเย็น      0
2  Your Verification key is 123456. Please do not...      0
3  เรียนคุณสมชาย ธนาคารกรุงเทพขอแจ้งว่าบัญชีของท่...      1
4  สวัสดีค่ะ คุณสมหมาย สำนักงานประกันสังคม โทรมาแ...      0

In [160]:
df_caller_exploded['label'].value_counts()

label
0    177
1    109
Name: count, dtype: int64

In [161]:
df_caller_joined['label'].value_counts()

label
0    124
1     55
Name: count, dtype: int64

# From English/AI parsed dataset

In [163]:
with open('original_data/archive/Thai_NonScam_Gemini.txt', 'r', encoding='utf-8') as f:
    nonscam_lines = [line.strip() for line in f.readlines()]

with open('original_data/archive/Thai_Scam_Gemini.txt', 'r', encoding='utf-8') as f:
    scam_lines = [line.strip() for line in f.readlines()]

label = [0 for x in nonscam_lines] + [1 for x in scam_lines]

data = {
    "text": nonscam_lines + scam_lines,
    "label": label
}

df_ai = pd.DataFrame(data)
df_ai = df_ai.sample(frac=1).reset_index(drop=True)

greetings = ["สวัสดีครับ","สวัสดีค่ะ",""]

def generate_bank_no():
    length = random.randint(10,14)
    digits = ''.join(random.choices("0123456789", k=length))

    indices = sorted(random.sample(range(1, length), random.randint(0,3)))

    parts = []
    last_idx = 0
    for idx in indices:
        parts.append(digits[last_idx:idx])
        last_idx = idx
    parts.append(digits[last_idx:])
    
    return "-".join(parts)

names = [
    "สมชาย", "สมศักดิ์", "อนุรักษ์", "กิตติชัย", "ไชยา", 
    "อาทิตย์", "ณัฐพงศ์", "ศราวุธ", "สันติ", "เกษม",
    "มะลิ", "กัญญา", "อารี", "รัตนา", "อัญชลี", 
    "ลออ", "ศิริพร", "บุษบา", "สุนารี", "จันทนา"
]

name_pattern = r"\[ชื่อ.*?\]"

df_ai['text'] = df_ai['text'].str.replace(
    name_pattern, 
    lambda m: random.choice(names), 
    regex=True
)

money_pattern = r"\[จำนวนเงิน.*?\]"

df_ai['text'] = df_ai['text'].str.replace(
    money_pattern, 
    lambda m: f"{round(random.randint(1000,30000), -2)}", 
    regex=True
)

day_pattern = r"\[วันที่\]"

df_ai['text'] = df_ai['text'].str.replace(
    day_pattern, 
    lambda m: f"{random.randint(1,31)}", 
    regex=True
)

df_ai['text'] = df_ai['text'].apply(lambda x: x.replace("[สวัสดีครับ/ค่ะ]", random.choice(greetings)))
df_ai['text'] = df_ai['text'].apply(lambda x: x.replace("[หมายเลขบัญชี]", generate_bank_no()))
df_ai['text'] = df_ai['text'].str.replace(r'[()]', '', regex=True)
df_ai['text'] = df_ai['text'].str.replace("...", "")
df_ai['text'] = df_ai['text'].str.replace('"', "")
df_ai['text'] = df_ai['text'].str.replace('"', "")

else_pattern = r"\[.*\]"

df_ai['text'] = df_ai['text'].str.replace(
    else_pattern, 
    lambda m: "", 
    regex=True
)

df_ai.to_csv('processed_data/ai.csv', index=False)
print("\n".join(df_ai[df_ai['text'].str.contains("[", regex=False)]['text'].tolist()))
# print("\n".join(df_ai[df_ai['text'].str.contains("\[*\]")]['text'].tolist()))

In [166]:
df_ai_and_caller_exploded = pd.concat([df_caller_exploded, df_ai], axis=0, ignore_index=True).sample(frac=1).reset_index(drop=True)
df_ai_and_caller_exploded.to_csv('processed_data/ai_and_caller_exploded.csv', index=False)

# combine ai + caller exploded + all audio final

In [3]:
ai_and_caller_exploded = pd.read_csv("processed_data/ai_and_caller_exploded.csv")
train_ai_and_caller_exploded, test_ai_and_caller_exploded = train_test_split(ai_and_caller_exploded, test_size=0.2, random_state=42)

all_audio_final_train = pd.read_csv("../STT_Thonburian_Whisper/final_transcription_files/all_audio_final_no_file_overlap_all_train.csv")
all_audio_final_test = pd.read_csv("../STT_Thonburian_Whisper/final_transcription_files/all_audio_final_no_file_overlap_all_test.csv")

final_train = pd.concat([train_ai_and_caller_exploded, all_audio_final_train], ignore_index=True)
final_train = final_train.sample(frac=1.0, random_state=42).reset_index(drop=True)

final_test = pd.concat([test_ai_and_caller_exploded, all_audio_final_test], ignore_index=True)
final_test = final_test.sample(frac=1.0, random_state=42).reset_index(drop=True)

print(f"train: {final_train['label'].value_counts()}")
print(f"test: {final_test['label'].value_counts()}")

final_train.to_csv("processed_data/all_data_final_no_file_overlap_all_train.csv", index=False)
print(f"Saved results to: processed_data/all_data_final_no_file_overlap_all_train.csv")

final_test.to_csv("processed_data/all_data_final_no_file_overlap_all_test.csv", index=False)
print(f"Saved results to: processed_data/all_data_final_no_file_overlap_all_test.csv")

train: label
0    1762
1    1152
Name: count, dtype: int64
test: label
0    348
1    212
Name: count, dtype: int64
Saved results to: processed_data/all_data_final_no_file_overlap_all_train.csv
Saved results to: processed_data/all_data_final_no_file_overlap_all_test.csv

# thaicentral

https://github.com/SLSCU/thai-dialect-corpus

In [25]:
thai_central = pd.read_csv("original_data/thaicentral.csv")
thai_central_augmented = thai_central.drop(['utterance', 'audio'], axis=1)
thai_central_augmented.columns = ['text']

random_indices = thai_central_augmented.sample(frac=0.5).index
thai_central_augmented.loc[random_indices, 'text'] = thai_central_augmented.loc[random_indices, 'text'].str.replace(' ', '', regex=False)

thai_central_augmented['label'] = 0

# thai_central_augmented.to_csv("processed_data/thai_central_augmented_all.csv", index=False)
# print(f"Saved results to: processed_data/thai_central_augmented_all.csv")

thai_central_augmented_sample = thai_central_augmented.sample(n=200)

thai_central_augmented_sample_train, thai_central_augmented_sample_test = train_test_split(thai_central_augmented_sample, test_size=0.2, random_state=42)

# thai_central_augmented_sample_train.to_csv("processed_data/thai_central_augmented_sample_train.csv", index=False)
# print(f"Saved results to: processed_data/thai_central_augmented_sample_train.csv")

# thai_central_augmented_sample_test.to_csv("processed_data/thai_central_augmented_sample_test.csv", index=False)
# print(f"Saved results to: processed_data/thai_central_augmented_sample_test.csv")

In [28]:
additional_data_train = pd.read_csv("processed_data/additional_data_1_splitted_train.csv")
additional_data_test = pd.read_csv("processed_data/additional_data_1_splitted_test.csv")

all_data_final_no_file_overlap_all_train = pd.read_csv("processed_data/all_data_final_no_file_overlap_all_train.csv")
all_data_final_no_file_overlap_all_test = pd.read_csv("processed_data/all_data_final_no_file_overlap_all_test.csv")

In [38]:
train_test_data = [
    [thai_central_augmented_sample_train, additional_data_train, all_data_final_no_file_overlap_all_train, "processed_data/additional_train_1.csv"],
    [thai_central_augmented_sample_test, additional_data_test, all_data_final_no_file_overlap_all_test, "processed_data/additional_test_1.csv"]
]

for thaicent_augmented_sample, additional_data, old_data, output_path in train_test_data:

    amount_to_sample = int((len(thaicent_augmented_sample)+len(additional_data)) * 0.25)

    old_sample = old_data.sample(n=amount_to_sample, random_state=42)

    combined_df = pd.concat([thaicent_augmented_sample, additional_data, old_sample])

    combined_df = combined_df.sample(frac=1).reset_index(drop=True)

    print(f"✅ Created Combined Dataset: {len(combined_df)} rows")
    print(f"   - {len(thaicent_augmented_sample)+len(additional_data)} New rows")
    print(f"   - {len(old_sample)} Old rows (Anchor)")

    # oversampling for training
    if "train" in output_path:
        scam_df = combined_df[combined_df['label'] == 1]
        normal_df = combined_df[combined_df['label'] == 0]

        print(f"Original Counts -> Normal: {len(normal_df)}, Scam: {len(scam_df)}")

        scam_oversampled = scam_df.sample(n=len(normal_df), replace=True, random_state=42)
        balanced_df = pd.concat([normal_df, scam_oversampled])
        balanced_df = balanced_df.sample(frac=1).reset_index(drop=True)

        print(f"New Counts -> Normal: {len(normal_df)}, Scam: {len(scam_oversampled)}")
        balanced_df.to_csv(output_path, index=False)
    else:
        combined_df.to_csv(output_path, index=False)

✅ Created Combined Dataset: 441 rows
   - 353 New rows
   - 88 Old rows (Anchor)
Original Counts -> Normal: 315, Scam: 126
New Counts -> Normal: 315, Scam: 315
✅ Created Combined Dataset: 128 rows
   - 103 New rows
   - 25 Old rows (Anchor)